name: Android Appium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      AVD_NAME: test
      API_LEVEL: 30
      TARGET: default
      EMULATOR: pixel
      APP_PATH: src/apps/android/androidAPP.apk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Download Android SDK tools
        uses: android-actions/setup-android@v3

      - name: Create Android emulator
        run: |
          echo "y" | sdkmanager --install "system-images;android-$API_LEVEL;$TARGET;$EMULATOR"
          avdmanager create avd -n $AVD_NAME -k "system-images;android-$API_LEVEL;$TARGET;$EMULATOR" --force

      - name: Start emulator
        run: |
          nohup emulator -avd $AVD_NAME -no-window -no-audio -no-boot-anim &
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Wait for emulator to boot
        run: |
          bootanim="$(adb shell getprop init.svc.bootanim)"
          until [ "$bootanim" = "stopped" ]; do
            sleep 5
            bootanim="$(adb shell getprop init.svc.bootanim)"
          done

      - name: Install Appium
        run: |
          npm install -g appium@2
          appium driver install uiautomator2

      - name: Start Appium server
        run: |
          nohup appium --port 4723 &
          sleep 10

      - name: Grant execute permissions to Maven wrapper
        run: chmod +x mvnw || true

      - name: Build with Maven
        run: ./mvnw clean install -DskipTests

      - name: Run tests
        run: ./mvnw test

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/ 